/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 2
 */

export namespace RNCAsyncStorage {
  export const NAME = 'RNCAsyncStorage' as const

  export interface Spec {
    multiGet(keys: string[], callback: (error: unknown[], result: unknown[]) => void): void;

    multiSet(kvPairs: unknown[], callback: (error: unknown[]) => void): void;

    multiRemove(keys: string[], callback: (error: unknown[]) => void): void;

    multiMerge(kvPairs: unknown[], callback: (error: unknown[]) => void): void;

    getAllKeys(callback: (error: unknown[], result: unknown[]) => void): void;

    clear(callback: (error: unknown[]) => void): void;

  }
}
